# Generated by Django 4.0 on 2022-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_remove_task_discription_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_progresss',
            field=models.BooleanField(default=False),
        ),
    ]
